package helperGit

const (
	gitCommandClone = "clone"
	gitCommandInit = "init"
	gitCommandAdd = "add"
	gitCommandMv = "mv"
	gitCommandReset = "reset"
	gitCommandRm = "rm"
	gitCommandBisect = "bisect"
	gitCommandGrep = "grep"
	gitCommandLog = "log"
	gitCommandShow = "show"
	gitCommandStatus = "status"
	gitCommandBranch = "branch"
	gitCommandCheckout = "checkout"
	gitCommandCommit = "commit"
	gitCommandDiff = "diff"
	gitCommandMerge = "merge"
	gitCommandRebase = "rebase"
	gitCommandTag = "tag"
	gitCommandFetch = "fetch"
	gitCommandPull = "pull"
	gitCommandPush = "push"
)