// Code generated by github.com/ungerik/pkgreflect DO NOT EDIT.

package helperGithub

import "reflect"

var Types = map[string]reflect.Type{
	"TypeGetRepositories": reflect.TypeOf((*TypeGetRepositories)(nil)).Elem(),
	"TypeGetRepository": reflect.TypeOf((*TypeGetRepository)(nil)).Elem(),
	"TypeLogin": reflect.TypeOf((*TypeLogin)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{
	"GitHubGetBranch": reflect.ValueOf(GitHubGetBranch),
	"GitHubGetOrganization": reflect.ValueOf(GitHubGetOrganization),
	"GitHubLogin": reflect.ValueOf(GitHubLogin),
}

var Variables = map[string]reflect.Value{
	"GetHelpers": reflect.ValueOf(&GetHelpers),
}

var Consts = map[string]reflect.Value{
}

