// Code generated by github.com/ungerik/pkgreflect DO NOT EDIT.

package helperSystem

import "reflect"

var Types = map[string]reflect.Type{
	"Environment": reflect.TypeOf((*Environment)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{
	"GetEnv": reflect.ValueOf(GetEnv),
	"HelperUserPrompt": reflect.ValueOf(HelperUserPrompt),
	"HelperUserPromptHidden": reflect.ValueOf(HelperUserPromptHidden),
	"PrintEnv": reflect.ValueOf(PrintEnv),
}

var Variables = map[string]reflect.Value{
	"GetHelpers": reflect.ValueOf(&GetHelpers),
}

var Consts = map[string]reflect.Value{
	"HelperPrefix": reflect.ValueOf(HelperPrefix),
}

