// Code generated by github.com/ungerik/pkgreflect DO NOT EDIT.

package helperUx

import "reflect"

var Types = map[string]reflect.Type{
}

var Functions = map[string]reflect.Value{
	"HelperPrintError": reflect.ValueOf(HelperPrintError),
	"HelperPrintf": reflect.ValueOf(HelperPrintf),
	"HelperPrintfBlue": reflect.ValueOf(HelperPrintfBlue),
	"HelperPrintfCyan": reflect.ValueOf(HelperPrintfCyan),
	"HelperPrintfError": reflect.ValueOf(HelperPrintfError),
	"HelperPrintfGreen": reflect.ValueOf(HelperPrintfGreen),
	"HelperPrintfMagenta": reflect.ValueOf(HelperPrintfMagenta),
	"HelperPrintfOk": reflect.ValueOf(HelperPrintfOk),
	"HelperPrintfRed": reflect.ValueOf(HelperPrintfRed),
	"HelperPrintfWarning": reflect.ValueOf(HelperPrintfWarning),
	"HelperPrintfWhite": reflect.ValueOf(HelperPrintfWhite),
	"HelperPrintfYellow": reflect.ValueOf(HelperPrintfYellow),
	"HelperPrintfln": reflect.ValueOf(HelperPrintfln),
	"HelperPrintflnBlue": reflect.ValueOf(HelperPrintflnBlue),
	"HelperPrintflnCyan": reflect.ValueOf(HelperPrintflnCyan),
	"HelperPrintflnError": reflect.ValueOf(HelperPrintflnError),
	"HelperPrintflnGreen": reflect.ValueOf(HelperPrintflnGreen),
	"HelperPrintflnMagenta": reflect.ValueOf(HelperPrintflnMagenta),
	"HelperPrintflnOk": reflect.ValueOf(HelperPrintflnOk),
	"HelperPrintflnRed": reflect.ValueOf(HelperPrintflnRed),
	"HelperPrintflnWarning": reflect.ValueOf(HelperPrintflnWarning),
	"HelperPrintflnWhite": reflect.ValueOf(HelperPrintflnWhite),
	"HelperPrintflnYellow": reflect.ValueOf(HelperPrintflnYellow),
	"HelperPrintln": reflect.ValueOf(HelperPrintln),
}

var Variables = map[string]reflect.Value{
	"GetHelpers": reflect.ValueOf(&GetHelpers),
}

var Consts = map[string]reflect.Value{
	"HelperPrefix": reflect.ValueOf(HelperPrefix),
	"OnlyOnce": reflect.ValueOf(OnlyOnce),
}

