// Code generated by github.com/ungerik/pkgreflect DO NOT EDIT.

package helperUx

import "reflect"

var Types = map[string]reflect.Type{
}

var Functions = map[string]reflect.Value{
	"HelperPrintError": reflect.ValueOf(HelperPrintError),
	"HelperPrintf": reflect.ValueOf(HelperPrintf),
	"HelperPrintfBlue": reflect.ValueOf(HelperPrintfBlue),
	"HelperPrintfCyan": reflect.ValueOf(HelperPrintfCyan),
	"HelperPrintfError": reflect.ValueOf(HelperPrintfError),
	"HelperPrintfGreen": reflect.ValueOf(HelperPrintfGreen),
	"HelperPrintfMagenta": reflect.ValueOf(HelperPrintfMagenta),
	"HelperPrintfOk": reflect.ValueOf(HelperPrintfOk),
	"HelperPrintfRed": reflect.ValueOf(HelperPrintfRed),
	"HelperPrintfWarning": reflect.ValueOf(HelperPrintfWarning),
	"HelperPrintfWhite": reflect.ValueOf(HelperPrintfWhite),
	"HelperPrintfYellow": reflect.ValueOf(HelperPrintfYellow),
}

var Variables = map[string]reflect.Value{
	"GetHelpers": reflect.ValueOf(&GetHelpers),
}

var Consts = map[string]reflect.Value{
	"HelperPrefix": reflect.ValueOf(HelperPrefix),
}

