// Code generated by github.com/ungerik/pkgreflect DO NOT EDIT.

package helpers

import "reflect"

var Types = map[string]reflect.Type{
}

var Functions = map[string]reflect.Value{
	"DiscoverHelpers": reflect.ValueOf(DiscoverHelpers),
}

var Variables = map[string]reflect.Value{
}

var Consts = map[string]reflect.Value{
}

