// Code generated by github.com/ungerik/pkgreflect DO NOT EDIT.

package helpers

import "reflect"

var Types = map[string]reflect.Type{
	"Files": reflect.TypeOf((*Files)(nil)).Elem(),
	"Helper": reflect.TypeOf((*Helper)(nil)).Elem(),
	"Helpers": reflect.TypeOf((*Helpers)(nil)).Elem(),
	"SortedHelpers": reflect.TypeOf((*SortedHelpers)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{
	"AddHelpers": reflect.ValueOf(AddHelpers),
	"DiscoverHelpers": reflect.ValueOf(DiscoverHelpers),
	"PrintHelpers": reflect.ValueOf(PrintHelpers),
}

var Variables = map[string]reflect.Value{
}

var Consts = map[string]reflect.Value{
	"HelperPrefix": reflect.ValueOf(HelperPrefix),
	"OnlyOnce": reflect.ValueOf(OnlyOnce),
}

