// Code generated by github.com/ungerik/pkgreflect DO NOT EDIT.

package jsonTemplate

import "reflect"

var Types = map[string]reflect.Type{
	"Exec": reflect.TypeOf((*Exec)(nil)).Elem(),
	"ExecArgs": reflect.TypeOf((*ExecArgs)(nil)).Elem(),
	"FileInfo": reflect.TypeOf((*FileInfo)(nil)).Elem(),
	"Template": reflect.TypeOf((*Template)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{
	"PrintHelpers": reflect.ValueOf(PrintHelpers),
	"UnescapeString": reflect.ValueOf(UnescapeString),
}

var Variables = map[string]reflect.Value{
}

var Consts = map[string]reflect.Value{
}

