// Code generated by github.com/ungerik/pkgreflect DO NOT EDIT.

package helperExec

import "reflect"

var Types = map[string]reflect.Type{
	"TypeExecCommand": reflect.TypeOf((*TypeExecCommand)(nil)).Elem(),
	"TypeExecCommandGetter": reflect.TypeOf((*TypeExecCommandGetter)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{
	"ExecCommand": reflect.ValueOf(ExecCommand),
	"HelperExec": reflect.ValueOf(HelperExec),
	"HelperExecCommand": reflect.ValueOf(HelperExecCommand),
	"HelperOsExit": reflect.ValueOf(HelperOsExit),
	"NewExecCommand": reflect.ValueOf(NewExecCommand),
	"ReflectExecCommand": reflect.ValueOf(ReflectExecCommand),
}

var Variables = map[string]reflect.Value{
	"GetHelpers": reflect.ValueOf(&GetHelpers),
}

var Consts = map[string]reflect.Value{
	"HelperPrefix": reflect.ValueOf(HelperPrefix),
}

