// Code generated by github.com/ungerik/pkgreflect DO NOT EDIT.

package helperFile

import "reflect"

var Types = map[string]reflect.Type{
	"HelperOsPath": reflect.TypeOf((*HelperOsPath)(nil)).Elem(),
	"OsPathGetter": reflect.TypeOf((*OsPathGetter)(nil)).Elem(),
	"State": reflect.TypeOf((*State)(nil)).Elem(),
	"TypeOsPath": reflect.TypeOf((*TypeOsPath)(nil)).Elem(),
	"TypeRsync": reflect.TypeOf((*TypeRsync)(nil)).Elem(),
}

var Functions = map[string]reflect.Value{
	"HelperChdir": reflect.ValueOf(HelperChdir),
	"HelperChmod": reflect.ValueOf(HelperChmod),
	"HelperCopyFiles": reflect.ValueOf(HelperCopyFiles),
	"HelperGetCwd": reflect.ValueOf(HelperGetCwd),
	"HelperReadFile": reflect.ValueOf(HelperReadFile),
	"HelperRsync": reflect.ValueOf(HelperRsync),
	"HelperWriteFile": reflect.ValueOf(HelperWriteFile),
	"NewOsPath": reflect.ValueOf(NewOsPath),
	"ReflectFileMode": reflect.ValueOf(ReflectFileMode),
	"ReflectPath": reflect.ValueOf(ReflectPath),
}

var Variables = map[string]reflect.Value{
	"GetHelpers": reflect.ValueOf(&GetHelpers),
}

var Consts = map[string]reflect.Value{
	"DefaultSeparator": reflect.ValueOf(DefaultSeparator),
	"HelperPrefix": reflect.ValueOf(HelperPrefix),
}

